import 'package:get/get_navigation/src/root/internacionalization.dart';

class Tranzilation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "اختر اللغة",
          "2": "اختر المنتجات",
          "3": "نحن لدينا أكثر من 100 ألف منتج، اختر \n منتجك من متجرنا",
          "4": "سهل وآمن للشراء",
          "5": "يمكنك الدفع نقدًا أو عبر بوابات الدفع الإلكترونية",
          "6": "تتبع طلبك",
          "7": "يمكنك تتبع طلبك في كل مرحلة \n وأيضًا عبر الخريطة",
          "8": "التوصيل",
          "9": "يمكنك طلب المنتج واستلامه من أي مكان",
          "10": "متابعة",
          "11": "أهلا بك",
          "12":
              "يمكنك تسجيل الدخول باستخدام البريد الإلكتروني وكلمة المرور أو عبر وسائل التواصل الاجتماعي",
          "13": "أدخل البريد الإلكتروني",
          "14": "أدخل كلمة المرور",
          "15": "هل نسيت كلمة المرور؟",
          "16": "تسجيل الدخول",
          "17": "ليس لديك حساب؟",
          "18": "إنشاء حساب",
          "19": "البريد الإلكتروني",
          "20": "كلمة المرور",
          "21": "اسم المستخدم",
          "22": "رقم الهاتف",
          "23": "أدخل رقم الهاتف",
          "24": "أدخل اسم المستخدم",
          "25":
              "أنشئ حسابًا باستخدام البريد الإلكتروني وكلمة المرور أو عبر وسائل التواصل الاجتماعي",
          "26": "لديك حساب؟",
          "27": "تسجيل الدخول",
          "28": "تحقق من البريد الإلكتروني",
          "29": "تم إنشاء الحساب بنجاح",
          "30": "الرجاء إدخال بريدك الإلكتروني لتلقي رمز التحقق",
          "31": "تحقق",
          "32": "الذهاب إلى تسجيل الدخول",
          "33": "نجاح",
          "34": "حفظ",
          "35": "الرجاء إدخال كلمة المرور الجديدة",
          "36": "كلمة المرور الجديدة",
          "37": "تمت إعادة تعيين كلمة المرور بنجاح",
          "38": "تهانينا",
          "39": "تم التسجيل بنجاح"
        },
        "en": {
          "1": "Choose Language",
          "2": "Choose Products",
          "3":
              "We have more than 100K products, \n choose your product from our store",
          "4": "Easy and Secure Shopping",
          "5": "You can pay in cash or viaza online payment gateways",
          "6": "Track Your Order",
          "7":
              "You can track your order at every stage \n and also through the map",
          "8": "Delivery",
          "9": "You can order your product and receive it anywhere",
          "10": "Continue",
          "11": "Welcome",
          "12":
              "Sign in using your email and password or continue with social media",
          "13": "Enter your email",
          "14": "Enter your password",
          "15": "Forgot password?",
          "16": "Sign In",
          "17": "Don't have an account?",
          "18": "Sign Up",
          "19": "Email",
          "20": "Password",
          "21": "Username",
          "22": "Phone Number",
          "23": "Enter your phone number",
          "24": "Enter your username",
          "25":
              "Sign up using your email and password or continue with social media",
          "26": "Already have an account?",
          "27": "Sign In",
          "28": "Check Email",
          "29": "Account created successfully",
          "30": "Please enter your email to receive a verification code",
          "31": "Check",
          "32": "Go to Login",
          "33": "Success",
          "34": "Save",
          "35": "Please enter your new password",
          "36": "New Password",
          "37": "Password reset successfully",
          "38": "Congratulations",
          "39": "Successfully registered"
        }
      };
}
